name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/checkout@v4
      with:
        node-version: '20'  # Use the Node.js version that matches your project's requirements

    - name: Install dependencies
      run: npm install

    - name: Install Playwright
      run: npx playwright install

    - name: Determine if specific test should run
      id: check_test
      run: |
        if [ -f ".no-data-target-strict-validation" ]; then
          echo "RUN_SPECIFIC_TEST=false" >> $GITHUB_ENV
        else
          echo "RUN_SPECIFIC_TEST=true" >> $GITHUB_ENV
        fi

    - name: Run tests
      run: |
        if [ "$RUN_SPECIFIC_TEST" = "true" ]; then
          npx playwright test
        else
          npx playwright test --grep '!data-target-strict-validation'
        fi

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results
